# Generated by Django 4.0.4 on 2022-07-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='', upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
