# Generated by Django 4.0.4 on 2022-07-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='mail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
