# Generated by Django 4.0.4 on 2022-07-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=None, max_length=3)),
                ('SKU', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxes',
            },
        ),
        migrations.CreateModel(
            name='Petitfours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('unit', models.FloatField(blank=None, max_length=3)),
                ('price', models.FloatField(blank=None, max_length=3)),
                ('SKU', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Petit Four',
                'verbose_name_plural': 'Petit Fours',
            },
        ),
        migrations.CreateModel(
            name='Tortas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('weight', models.FloatField(blank=None, max_length=3)),
                ('price', models.FloatField(blank=None, max_length=3)),
                ('SKU', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Torta',
                'verbose_name_plural': 'Tortas',
            },
        ),
    ]
