# Generated by Django 4.0.4 on 2022-07-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='ingredients',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='petitfours',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='petitfours',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='petitfours',
            name='price',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='petitfours',
            name='unit',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tortas',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tortas',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tortas',
            name='price',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tortas',
            name='weight',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
    ]
