# Generated by Django 4.0.4 on 2022-07-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_box_description_alter_box_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tortas',
            name='SKU',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
