# Generated by Django 4.0.4 on 2022-07-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_tortas_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='petitfours',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='tortas',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='box',
            name='SKU',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='petitfours',
            name='SKU',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
