# Generated by Django 4.0.4 on 2022-07-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_active_box_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tortas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tortas'),
        ),
    ]
